import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {decodePinned,encodePinned,inspectConfiguration,reviewTransfer,transferLayout} from '../src/core.mjs';
const bytes=s=>new TextEncoder().encode(s),text=b=>new TextDecoder().decode(b);
function filter(id,{source=false,offset=0}={}){
 const names=['id','name','status','note'];
 const binds=names.map((name,i)=>`<attribute attrEntryId="fa${i+offset}" name="${name}" typeName="TEXT" typeId="12" dataKind="STRING" ordinalPosition="${i}" maxLength="0" isRequired="false" isAutoGenerated="false"/>`).join('');
 const constraints=names.map((name,i)=>{
  const pos=source?[0,2,1,3][i]:i;
  let attrs=source&&name==='note'?' visible="false"':'';
  if(source&&name==='status')attrs+=' order="1" orderDesc="false"';
  if(source&&name==='id')attrs+=' order="2" orderDesc="true"';
  return `<constraint name="${name}" attrEntryId="fa${i+offset}" pos="${pos}"${attrs} criteria="${source?'SOURCE_SECRET':'TARGET_ONLY'}"><value>opaque-${name}</value><option name="other">opaque-keep-${name}</option>${source&&name==='id'?`<option name="pinned">${encodePinned(0)}</option>`:''}</constraint>`;
 }).join('');
 return `<filter objectId="${id}" anyConstraint="false" where="${source?'SOURCE_PREDICATE':'TARGET_PREDICATE'}"><flatten-attribute-bindings>${binds}</flatten-attribute-bindings>${constraints}</filter>`;
}
const doc=(...fs)=>`<?xml version="1.0" encoding="UTF-8"?><data-filters>${fs.join('')}</data-filters>`;
const source=doc(filter('source',{source:true})),unrelated=filter('untouched'),target=doc(filter('target',{offset:20}),unrelated);
const apply=(s=source,t=target)=>transferLayout(bytes(s),bytes(t),'source','target');
test('Copies only four-column layout with independent literal expected fields',()=>{
 const {bytes:out,receipt}=apply();const s=text(out);assert(!s.includes('SOURCE_'));assert(s.includes(unrelated));
 assert.deepEqual(receipt.columns.map(c=>c.after),[
  {name:'id',position:0,visible:true,sortPriority:2,descending:true,pinIndex:0},
  {name:'name',position:2,visible:true,sortPriority:null,descending:false,pinIndex:null},
  {name:'status',position:1,visible:true,sortPriority:1,descending:false,pinIndex:null},
  {name:'note',position:3,visible:false,sortPriority:null,descending:false,pinIndex:null},
 ]);
 assert.equal((s.match(/TARGET_ONLY/g)||[]).length,8);assert.equal((s.match(/TARGET_PREDICATE/g)||[]).length,2);
 for(let i=20;i<24;i++)assert(s.includes(`attrEntryId="fa${i}"`));
 assert.equal(s.match(/<flatten-attribute-bindings>[\s\S]*?<\/flatten-attribute-bindings>/)[0],target.match(/<flatten-attribute-bindings>[\s\S]*?<\/flatten-attribute-bindings>/)[0]);
});
test('All bytes outside selected layout tokens remain exact',()=>{
 const strip=s=>s.replace(/\s(?:pos|visible|order|orderDesc)="[^"]*"/g,'').replace(/<option name="pinned">[^<]*<\/option>/g,'');
 assert.equal(strip(text(apply().bytes)),strip(target));
});
test('Repeated transfer is a byte-identical no-op',()=>{const first=apply().bytes;assert.deepEqual(transferLayout(bytes(source),first,'source','target').bytes,first);});
test('Removing a pin preserves opaque siblings',()=>{
 const pinnedTarget=doc(filter('target',{source:true,offset:20}),unrelated),plainSource=doc(filter('source'));
 const result=text(apply(plainSource,pinnedTarget).bytes);assert(!result.includes('name="pinned"'));assert(result.includes('<option name="other">opaque-keep-id</option>'));
});
test('Adds canonical pin to self-closing native constraint',()=>{
 const t=target.replace(/(<constraint name="id"[^>]+)>[\s\S]*?<\/constraint>/,'$1/>');const out=text(apply(source,t).bytes);
 assert(out.includes(`<option name="pinned">${encodePinned(0)}</option></constraint>`));
});
test('Valid gapped pin indices are preserved, not renumbered',()=>{
 const s=source.replace(encodePinned(0),encodePinned(255));assert.equal(apply(s).receipt.columns[0].after.pinIndex,255);
});
test('Fixed whitelist covers exactly256 unique encodings',()=>{
 const all=new Set();for(let i=0;i<256;i++){const v=encodePinned(i);all.add(v);assert.equal(decodePinned(v),i);}assert.equal(all.size,256);
});
test('Whitelist equals every encoding actually emitted by the pinned official bundled JDK',()=>{
 const raw=readFileSync(new URL('./fixtures/pinned-values-jdk.json',import.meta.url));
 assert.equal(createHash('sha256').update(raw).digest('hex'),'e8e0f7836790451dc4b4614f69ca3caf9fbc4b808122df6d13cc291e367e22c7');
 const actual=JSON.parse(raw);assert.equal(actual.length,256);
 for(let i=0;i<256;i++){assert.equal(encodePinned(i),actual[i]);assert.equal(decodePinned(actual[i]),i);}
});
for(const value of [encodePinned(0)+'AA==',' '+encodePinned(0),encodePinned(0)+'\n',encodePinned(0).slice(0,-1),encodePinned(0).replace('SW50','U3Ry'),'rO0ABXQABHRlc3Q=','', '<serialized>'])test('Rejects noncanonical pinned form '+JSON.stringify(value).slice(0,30),()=>assert.throws(()=>decodePinned(value)));
for(const n of [-1,256,1.5,NaN,'0'])test('Rejects invalid pin integer '+n,()=>assert.throws(()=>encodePinned(n)));
const malformed=[
 ['DTD',s=>s.replace('<data-filters>','<!DOCTYPE data-filters><data-filters>')],
 ['entity declaration',s=>s.replace('<data-filters>','<!ENTITY x SYSTEM "https://example.invalid"><data-filters>')],
 ['numeric null',s=>s.replace('SOURCE_PREDICATE','&#0;')],
 ['literal null',s=>s+'\0'],
 ['numeric surrogate',s=>s.replace('SOURCE_PREDICATE','&#xD800;')],
 ['namespace',s=>s.replace('<data-filters>','<data-filters xmlns="urn:test">')],
 ['duplicate object',s=>doc(filter('source',{source:true}),filter('source'))],
 ['duplicate name',s=>s.replace('<constraint name="name"','<constraint name="id"')],
 ['bad binding ref',s=>s.replace('name="id" attrEntryId="fa0"','name="id" attrEntryId="missing"')],
 ['duplicate binding name',s=>s.replace('name="name" typeName','name="id" typeName')],
 ['nested binding',s=>s.replace('name="id" typeName','name="id" parentAttrEntryId="fa9" typeName')],
 ['pseudo binding',s=>s.replace('name="id" typeName','name="id" isPseudoAttribute="true" typeName')],
 ['position collision',s=>s.replace('pos="2"','pos="0"')],
 ['noncanonical decimal',s=>s.replace('pos="0"','pos="00"')],
 ['invalid boolean',s=>s.replace('visible="false"','visible="0"')],
 ['duplicate sort priority',s=>s.replace('order="2"','order="1"')],
 ['direction without order',s=>s.replace(' order="2"','')],
 ['comment fragmented pin',s=>s.replace(encodePinned(0),encodePinned(0)+'<!--ignored-->')],
 ['entity encoded pin',s=>s.replace(encodePinned(0),'&#114;'+encodePinned(0).slice(1))],
 ['pin collision',s=>s.replace('<option name="other">opaque-keep-name</option>',`<option name="pinned">${encodePinned(0)}</option>`) ],
 ['hidden pinned',s=>s.replace('pos="0"','pos="0" visible="false"')],
 ['unknown selected child',s=>s.replace('</filter>','<extension/></filter>')],
 ['processing instruction',s=>s.replace('<data-filters>','<?resource file="x"?><data-filters>')],
 ['XML1.1 declaration',s=>s.replace('version="1.0"','version="1.1"')],
 ['uppercase declaration field',s=>s.replace('version=','VERSION=')],
 ['invalid standalone flag',s=>s.replace('encoding="UTF-8"','encoding="UTF-8" standalone="YES"')],
];
for(const [name,mutate] of malformed)test('Fails closed: '+name,()=>assert.throws(()=>apply(mutate(source))));
test('Exact column mismatch blocks rather than guesses',()=>assert.throws(()=>apply(source,target.replaceAll('name="note"','name="NOTE"'))));
test('Matching source/target aliases cannot hide a different referenced native column',()=>{
 const swap=s=>s.replace('<constraint name="id"','<constraint name="aliased_id"');
 assert.throws(()=>apply(swap(source),swap(target)),e=>e.code==='COLUMN_IDENTITY');
});
test('Existing target entry is mandatory',()=>assert.throws(()=>transferLayout(bytes(source),bytes(target),'source','missing')));
test('Opaque target values are untouched, never decoded',()=>{
 const opaque='rO0ABXQABHRlc3Q=';const t=target.replace('opaque-id',opaque);assert(text(apply(source,t).bytes).includes(`<value>${opaque}</value>`));
});
test('Malformed UTF8 and oversized input reject before XML parse',()=>{assert.throws(()=>inspectConfiguration(new Uint8Array([255])));assert.throws(()=>inspectConfiguration(new Uint8Array(4*1024*1024+1)));});
test('Element and depth caps reject during bounded token iteration',()=>{
 assert.throws(()=>inspectConfiguration(bytes('<data-filters>'+ '<x/>'.repeat(30001)+'</data-filters>')),e=>e.code==='XML_LIMIT');
 assert.throws(()=>inspectConfiguration(bytes('<data-filters>'+ '<x>'.repeat(33)+'</x>'.repeat(33)+'</data-filters>')),e=>e.code==='XML_LIMIT');
});

test('Lexical spans preserve unusual legal attribute whitespace and quoting',()=>{
 const t=target.replace('pos="0"',"\tpos \n= '0'").replace('criteria="TARGET_ONLY"','criteria = "TARGET_ONLY"');
 const out=text(apply(source,t).bytes);assert(out.includes("\tpos \n= '0'"));assert(out.includes('criteria = "TARGET_ONLY"'));
});
test('Apparent markup and declarations inside comments stay inert and exact',()=>{
 const comment='<!-- <?xml version="1.1"?> <constraint pos="99"/> &#0; <!DOCTYPE nope> -->';
 const t=target.replace('<data-filters>','<data-filters>'+comment);
 assert(text(apply(source,t).bytes).includes(comment));
});
for(const malformed of ['<','<x','<x a="','<!--unterminated','<!-- bad -- comment -->','<![CDATA[unterminated','<?xml ', '<x a="&unknown;"/>','<x a="1"a="2"/>','<x></y>'])test('Rejects malformed lexical input '+malformed,()=>assert.throws(()=>inspectConfiguration(bytes('<data-filters>'+malformed+'</data-filters>'))));
// Each adversarial parse is isolated and has a hard timeout/memory ceiling. A
// regressed lexer cannot hang the test runner before reporting a resource failure.
for(const mode of ['repeated-open','unterminated-comment','unterminated-cdata','unterminated-quote','unterminated-pi','comment-declarations','attribute-budget','token-budget','long-tag-whitespace'])test('Bounded lexical resource case: '+mode,()=>{
 const program=`
 import assert from 'node:assert/strict';
 import {inspectConfiguration,transferLayout} from ${JSON.stringify(new URL('../src/core.mjs',import.meta.url).href)};
 const mode=${JSON.stringify(mode)},encode=s=>new TextEncoder().encode(s);
 const small='<data-filters><filter objectId="x"/></data-filters>';
 let input,accept=false;
 if(mode==='repeated-open')input='<'.repeat(1024*1024);
 if(mode==='unterminated-comment')input='<!--'+'<'.repeat(1024*1024);
 if(mode==='unterminated-cdata')input='<data-filters><![CDATA['+'<'.repeat(1024*1024);
 if(mode==='unterminated-quote')input='<data-filters><filter objectId="'+'x'.repeat(1024*1024);
 if(mode==='unterminated-pi')input='<?xml '+'x'.repeat(1024*1024);
 if(mode==='comment-declarations'){input='<!--'+'<?xml '.repeat(150000)+'-->'+small;accept=true;}
 if(mode==='attribute-budget')input='<data-filters '+Array.from({length:10000},(_,i)=>'a'+i+'="v"').join(' ')+'/>';
 if(mode==='token-budget')input='<data-filters>'+'<!---->'.repeat(80001)+'<filter objectId="x"/></data-filters>';
 if(mode==='long-tag-whitespace'){
   const source=${JSON.stringify(source)},target=${JSON.stringify(target)}.replace('pos="0"','pos="0"'+' '.repeat(1024*1024));
   const out=transferLayout(encode(source),encode(target),'source','target');assert.equal(out.receipt.changedColumns,4);process.exit(0);
 }
 if(accept)assert.deepEqual(inspectConfiguration(encode(input)).entries,['x']);
 else assert.throws(()=>inspectConfiguration(encode(input)));
 `;
 const child=spawnSync(process.execPath,['--max-old-space-size=128','--input-type=module','--eval',program],{timeout:5000,maxBuffer:16384});
 assert.equal(child.error,undefined,`${mode}: ${child.error}`);assert.equal(child.status,0,`${mode}: ${child.stderr}`);
});

test('Actual GUI-authored fixture retains every protected byte and literal native layout',()=>{
 const original=readFileSync(new URL('./fixtures/native-authored.xml',import.meta.url));
 const hash=b=>createHash('sha256').update(b).digest('hex');
 assert.equal(hash(original),'81ce1b826a09fc351188fc43554961e017bf80dd14ba40a1373c5f8c75c8a5c4');
 const result=transferLayout(original,original,'GridPass Fixture@@/@@source_table','GridPass Fixture@@/@@target_table');
 assert.equal(hash(result.bytes),'e65c4d1585e31ee1ba7c1f7b8292452ed61654a57e8250883aec0c386b3f2639');
 assert.equal(hash(original),'81ce1b826a09fc351188fc43554961e017bf80dd14ba40a1373c5f8c75c8a5c4');
 assert.equal((text(result.bytes).match(/isPseudoAttribute="false"/g)||[]).length,12);
 assert(text(result.bytes).includes('typeName="VARCHAR"'));
});
