import {chromium,expect} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const art=resolve('artifacts/browser');await mkdir(art,{recursive:true});
const sha=b=>createHash('sha256').update(b).digest('hex');
const fixture=await readFile('test/fixtures/native-authored.xml'),shipped=await readFile('dist/grid-pass.html');
const sourceId='GridPass Fixture@@/@@source_table',targetId='GridPass Fixture@@/@@target_table';
// Handwritten exact byte changes, independent of the production module.
const pin0='rO0ABXNyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAAAA';
const raw=fixture.toString(),start=raw.indexOf('<filter objectId="'+targetId+'"'),end=raw.indexOf('</filter>',start)+9;
let selected=raw.slice(start,end);
selected=selected.replace('<constraint name="id" pos="0" attrEntryId="fa0"/>','<constraint name="id" pos="0" attrEntryId="fa0" order="2" orderDesc="true"><option name="pinned">'+pin0+'</option></constraint>');
selected=selected.replace('<constraint name="name" pos="1"','<constraint name="name" pos="2"').replace('<option name="pinned">'+pin0+'</option>\n\t\t</constraint>','\n\t\t</constraint>');
selected=selected.replace('<constraint name="status" pos="2" operator="NOT_EQUALS" attrEntryId="fa2">','<constraint name="status" pos="1" operator="NOT_EQUALS" attrEntryId="fa2" order="1" orderDesc="false">');
selected=selected.replace('<constraint name="note" pos="3" attrEntryId="fa3"/>','<constraint name="note" pos="3" attrEntryId="fa3" visible="false"/>');
const expected=Buffer.from(raw.slice(0,start)+selected+raw.slice(end));
expect(sha(fixture)).toBe('81ce1b826a09fc351188fc43554961e017bf80dd14ba40a1373c5f8c75c8a5c4');
expect(sha(expected)).toBe('e65c4d1585e31ee1ba7c1f7b8292452ed61654a57e8250883aec0c386b3f2639');
const report={status:'RUNNING',cases:[],pageErrors:[],consoleErrors:[],networkRequests:[],screenshots:[],shippedHTMLSHA256:sha(shipped),downloads:{}};
const check=(name,details={})=>{report.cases.push({name,passed:true,...details});console.log('PASS',name);};
if(!process.env.CHROMIUM_PATH)throw Error('Use hosted sandboxed Chrome');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,chromiumSandbox:true});report.browserVersion=browser.version();
const commands=execFileSync('ps',['-eo','args'],{encoding:'utf8'}).split('\n').filter(s=>s.includes('--remote-debugging-pipe')&&s.includes('--user-data-dir=')&&/chrome|chromium/.test(s));
expect(commands.length).toBeGreaterThan(0);expect(commands.some(s=>s.includes('--no-sandbox')||s.includes('--disable-setuid-sandbox'))).toBe(false);report.chromiumMainProcessCommands=commands;
const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true});await context.setOffline(true);
const page=await context.newPage();let countDownloads=0;
function track(p){p.on('pageerror',e=>report.pageErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});p.on('request',r=>{if(/^https?:/.test(r.url()))report.networkRequests.push(r.url());});p.on('download',()=>countDownloads++);}
track(page);
const payload=(buffer,name)=>({buffer,name,mimeType:'application/xml'});
async function role(name,buffer=fixture,filename=`private-${name}.xml`){await page.locator(`#${name}-file`).setInputFiles(payload(buffer,filename));await expect(page.locator(`#${name}-meta`)).not.toContainText(/Reading|読み込んで/);}
async function choose(s=sourceId,t=targetId){await page.locator('#source-entry').selectOption(s);await page.locator('#target-entry').selectOption(t);}
async function load(){await role('source');await role('target');await choose();await expect(page.locator('#review-content')).toBeVisible();}
async function approve(){await page.locator('#confirm').check();await expect(page.locator('#export')).toBeEnabled();}
async function save(selector,name,keyboard=false){const wait=page.waitForEvent('download');if(keyboard){await page.locator(selector).focus();await page.keyboard.press('Enter');}else await page.locator(selector).click();const d=await wait;await d.saveAs(resolve(art,name));return readFile(resolve(art,name));}
async function shot(name,locator=page){await locator.screenshot({path:resolve(art,name),...(locator===page?{fullPage:true}:{})});report.screenshots.push(name);}
try{
 await page.goto(pathToFileURL(resolve('dist/grid-pass.html')).href);await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('#export')).toBeDisabled();check('Clean Japanese start with no selected entries or enabled export');
 const sourceChooser=page.waitForEvent('filechooser');await page.locator('#source-choose').focus();await page.keyboard.press('Enter');await (await sourceChooser).setFiles(payload(fixture,'private-source.xml'));await expect(page.locator('#source-meta')).toContainText('private-source.xml');await expect(page.locator('#source-file')).toHaveValue('');check('A keyboard chooser activation imports the file and clears the native input for reselection');await role('target');await expect(page.locator('#source-entry')).toHaveValue('');await expect(page.locator('#target-entry')).toHaveValue('');await expect(page.locator('#confirm')).toBeDisabled();check('Import requires explicit source and existing target entry choices');
 await choose();await expect(page.locator('#rows tr')).toHaveCount(4);await expect(page.locator('#confirm')).toBeEnabled();await expect(page.locator('#export')).toBeDisabled();
 expect(await page.locator('#before-order li').evaluateAll(ns=>ns.map(n=>n.childNodes[0].textContent))).toEqual(['name','id','status','note']);expect(await page.locator('#after-order li').evaluateAll(ns=>ns.map(n=>n.childNodes[0].textContent))).toEqual(['id','status','name','note']);
 expect(await page.locator('#after-order li.pinned').count()).toBe(1);await expect(page.locator('#after-order li.hidden-column')).toContainText('note');check('Exact original and transferred native layout order, pin and hidden column are reviewed');
 await page.locator('#confirm').focus();await page.keyboard.press('Space');const output=await save('#export','exported-layout.xml',true);expect(output.equals(expected)).toBe(true);const receiptBytes=await save('#receipt','layout-receipt.json');const receipt=JSON.parse(receiptBytes);
 expect(receipt.sourceSHA256).toBe(sha(fixture));expect(receipt.targetSHA256).toBe(sha(fixture));expect(receipt.outputSHA256).toBe(sha(output));expect(receipt.outputBytes).toBe(output.length);expect(receipt.sourceId).toBe(sourceId);expect(receipt.targetId).toBe(targetId);expect(receipt.changedColumns).toBe(4);expect(receipt.exportOrigin).toBe('browser UI download');
 expect(receipt.columns.map(c=>[c.name,c.after.position,c.after.visible,c.after.sortPriority,c.after.descending,c.after.pinIndex])).toEqual([['id',0,true,2,true,0],['name',2,true,null,false,null],['status',1,true,1,false,null],['note',3,false,null,false,null]]);
 expect(receipt.columns.every(c=>c.changed)).toBe(true);expect(receipt.sourceFile).toEqual({name:'private-source.xml',bytes:fixture.length,sha256:sha(fixture)});expect(receipt.targetFile).toEqual({name:'private-target.xml',bytes:fixture.length,sha256:sha(fixture)});
 report.downloads.primary={sha256:sha(output),bytes:output.length,receiptSHA256:sha(receiptBytes)};await writeFile(resolve(art,'source-input.xml'),fixture);await writeFile(resolve(art,'target-input.xml'),fixture);check('Actual keyboard XML download equals independent literal byte patch and complete receipt');
 expect((await save('#export','repeated-layout.xml')).equals(output)).toBe(true);expect((await save('#receipt','repeated-receipt.json')).equals(receiptBytes)).toBe(true);check('Repeated export and receipt are byte-identical');
 const reselection=page.waitForEvent('filechooser');await page.locator('#source-choose').focus();await page.keyboard.press('Enter');await (await reselection).setFiles(payload(fixture,'private-source.xml'));await expect(page.locator('#source-entry')).toHaveValue('');await expect(page.locator('#confirm')).not.toBeChecked();await expect(page.locator('#receipt')).toBeDisabled();await expect(page.locator('#export')).toBeDisabled();await choose();await approve();check('Reselecting the same file through the chooser invalidates selection, approval and receipt');
 for(const language of ['ja','en']){
  await page.locator('#lang-'+language).click();await expect(page.locator('html')).toHaveAttribute('lang',language);await expect(page.locator('#confirm')).not.toBeChecked();await approve();await shot(`01-${language}-desktop.png`);
  await page.pdf({path:resolve(art,`02-${language}-review.pdf`),format:'A4',printBackground:true});const pdftext=execFileSync('pdftotext',[resolve(art,`02-${language}-review.pdf`),'-'],{encoding:'utf8'});for(const token of ['GridPass','private-source.xml','private-target.xml','source_table','target_table','id','name','status','note'])expect(pdftext).toContain(token);expect(execFileSync('pdfinfo',[resolve(art,`02-${language}-review.pdf`)],{encoding:'utf8'})).toMatch(/Pages:\s+1\b/);execFileSync('pdftoppm',['-scale-to','1400','-png','-singlefile',resolve(art,`02-${language}-review.pdf`),resolve(art,`02-${language}-review`)]);report.screenshots.push(`02-${language}-review.png`);check(`${language} one-page print contains exact selected source/target identities and all columns`);
  for(const width of [390,320]){
   await page.setViewportSize({width,height:900});await page.locator('.table-wrap').evaluate(e=>e.scrollLeft=0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(language==='ja'){const lines=await page.evaluate(()=>{const count=selector=>{const range=document.createRange();range.selectNodeContents(document.querySelector(selector));return new Set([...range.getClientRects()].filter(r=>r.width>0).map(r=>Math.round(r.top))).size;};return {headline:count('.intro h1'),scope:count('.scope strong')};});expect(lines).toEqual({headline:2,scope:1});check(`Japanese ${width}px headings preserve complete lines`,lines);}await shot(`03-${language}-${width}-left.png`);
   await page.locator('.table-wrap').evaluate(e=>e.scrollLeft=e.scrollWidth);const bounds=await page.locator('.table-wrap').evaluate(e=>{const r=e.getBoundingClientRect(),c=e.querySelector('tbody tr td:last-child').getBoundingClientRect();return {left:r.left,right:r.right,cellLeft:c.left,cellRight:c.right,headerLeft:e.querySelector('thead th:last-child').getBoundingClientRect().left,headerRight:e.querySelector('thead th:last-child').getBoundingClientRect().right,header:e.querySelector('thead th:last-child').textContent,scroll:e.scrollLeft};});expect(bounds.scroll).toBeGreaterThan(0);expect(bounds.cellLeft).toBeGreaterThanOrEqual(bounds.left-2);expect(bounds.cellRight).toBeLessThanOrEqual(bounds.right+2);expect(bounds.headerLeft).toBeGreaterThanOrEqual(bounds.left-2);expect(bounds.headerRight).toBeLessThanOrEqual(bounds.right+2);expect(bounds.header).toBe(language==='ja'?'変更':'Change');await shot(`03-${language}-${width}-right.png`,page.locator('#review'));check(`${language} ${width}px review has no page overflow and its final table column is reachable`,bounds);
  }
  await page.setViewportSize({width:1440,height:1050});await page.locator('.table-wrap').evaluate(e=>e.scrollLeft=0);
 }
 await page.locator('#target-entry').selectOption('GridPass Fixture@@/@@unrelated_table');await expect(page.locator('#confirm')).not.toBeChecked();await expect(page.locator('#receipt')).toBeDisabled();await expect(page.locator('#review-identities')).toContainText('unrelated_table');check('Changing the target invalidates prior confirmation and receipt');
 await page.locator('#source-entry').selectOption('GridPass Fixture@@/@@target_table');await page.locator('#target-entry').selectOption(targetId);await expect(page.locator('#change-count')).toContainText('0 columns change');await approve();expect((await save('#export','unchanged-layout.xml')).equals(fixture)).toBe(true);check('Selecting the same existing layout produces an exact byte-preserving no-op');
 await load();await approve();await page.locator('#target-file').evaluate(e=>{e.value='';e.dispatchEvent(new Event('change',{bubbles:true}));});await expect(page.locator('#review-content')).toBeHidden();await expect(page.locator('#export')).toBeDisabled();await expect(page.locator('#receipt')).toBeDisabled();check('Dispatched empty target-file change clears stale review and export');
 const bads=[
  ['DTD',Buffer.from(raw.replace('<data-filters>','<!DOCTYPE data-filters SYSTEM "https://example.invalid/external.dtd"><data-filters>')),'XML_DOCTYPE'],
  ['invalid UTF8',Buffer.from([255,255]),'XML_ENCODING'],
  ['duplicate object',Buffer.from(raw.replace('GridPass Fixture@@/@@unrelated_table',targetId)),'DUPLICATE_OBJECT'],
  ['noncanonical pin',Buffer.from(raw.replace(pin0,'rO0ABXQABHRlc3Q=')),'PIN_ENCODING'],
  ['binding mismatch',Buffer.from(raw.replace('<constraint name="id" pos="0" order','<constraint name="wrong" pos="0" order')),'COLUMN_IDENTITY'],
  ['nested binding',Buffer.from(raw.replace('attrEntryId="fa0" isPseudoAttribute','attrEntryId="fa0" parentAttrEntryId="parent" isPseudoAttribute')),'BINDINGS'],
  ['ambiguous position',Buffer.from(raw.replace('<constraint name="name" pos="2"','<constraint name="name" pos="0"')),'LAYOUT_COLLISION'],
  ['oversized',Buffer.alloc(4*1024*1024+1,32),'INPUT_LIMIT'],
 ];
 for(const [name,buffer,code] of bads){await load();await approve();await role('source',buffer);if(await page.locator('#source-entry').isEnabled())await page.locator('#source-entry').selectOption(sourceId);await expect(page.locator('#error')).toContainText(code);await expect(page.locator('#export')).toBeDisabled();await expect(page.locator('#receipt')).toBeDisabled();await expect(page.locator('#review-content')).toBeHidden();check(`${name} blocks output and stale review`);}
 await shot('04-en-error.png');
 const mismatched=Buffer.from(raw.replaceAll('name="note"','name="NOTE"'));await role('source',fixture);await role('target',mismatched);await choose();await expect(page.locator('#error')).toContainText('COLUMN_MISMATCH');check('Exact cross-file column mismatch blocks instead of guessing names');
 const inert=Buffer.from(raw.replaceAll('name="note"','name="&lt;img src=x onerror=alert(1)&gt;"'));await role('source',inert);await role('target',inert);await choose();await expect(page.locator('#rows')).toContainText('<img src=x onerror=alert(1)>');expect(await page.locator('#rows img').count()).toBe(0);check('Decoded user labels are rendered only as text');
 await page.evaluate(()=>{window.readWaits=[];window.pendingReads=0;window.originalRead=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this.name==='slow.xml'){window.pendingReads++;await new Promise(resolve=>window.readWaits.push(resolve));try{return await window.originalRead.call(this);}finally{window.pendingReads--;}}return window.originalRead.call(this);};});
 await page.locator('#source-file').setInputFiles(payload(fixture,'slow.xml'));await expect.poll(()=>page.evaluate(()=>window.pendingReads)).toBe(1);await page.locator('#reset').click();await page.evaluate(()=>window.readWaits.splice(0).forEach(r=>r()));await expect.poll(()=>page.evaluate(()=>window.pendingReads)).toBe(0);await expect(page.locator('#source-entry')).toBeDisabled();await expect(page.locator('#review-content')).toBeHidden();check('Reset cancels an in-flight file read before it can restore state');
 await page.locator('#source-file').setInputFiles(payload(fixture,'slow.xml'));await expect.poll(()=>page.evaluate(()=>window.pendingReads)).toBe(1);await role('source',fixture,'new-source.xml');await page.evaluate(()=>window.readWaits.splice(0).forEach(r=>r()));await expect.poll(()=>page.evaluate(()=>window.pendingReads)).toBe(0);await expect(page.locator('#source-meta')).toContainText('new-source.xml');await page.evaluate(()=>File.prototype.arrayBuffer=window.originalRead);check('A later source file wins over an older delayed import');
 await load();await approve();await page.evaluate(()=>{window.hashWaits=[];window.pendingHashes=0;window.originalDigest=crypto.subtle.digest.bind(crypto.subtle);crypto.subtle.digest=async(...args)=>{window.pendingHashes++;await new Promise(resolve=>window.hashWaits.push(resolve));try{return await window.originalDigest(...args);}finally{window.pendingHashes--;}};});
 const before=countDownloads;await page.locator('#export').click();await expect.poll(()=>page.evaluate(()=>window.pendingHashes)).toBe(3);await page.locator('#target-entry').selectOption('GridPass Fixture@@/@@unrelated_table');await page.evaluate(()=>window.hashWaits.splice(0).forEach(r=>r()));await expect.poll(()=>page.evaluate(()=>window.pendingHashes)).toBe(0);await expect(page.locator('#receipt')).toBeDisabled();expect(countDownloads).toBe(before);await page.evaluate(()=>crypto.subtle.digest=window.originalDigest);check('Changing target during hashing cancels the stale download and receipt');
 const privateLabel='PRIVATE_COLUMN_b798a31',privateValue='PRIVATE_OPAQUE_d19b025';const privateInput=Buffer.from(raw.replaceAll('name="note"','name="'+privateLabel+'"').replace('<value>rO0ABXQAAUM=</value>','<value>'+privateValue+'</value>'));await role('source',privateInput);await role('target',privateInput);await choose();await approve();await expect(page.locator('#rows')).toContainText(privateLabel);const offline=await save('#offline','grid-pass-offline.html');expect(offline.toString()).not.toContain('private-source.xml');expect(offline.toString()).not.toContain('private-target.xml');expect(offline.toString()).not.toContain(privateLabel);expect(offline.toString()).not.toContain(privateValue);
 const reopened=await context.newPage();track(reopened);await reopened.goto(pathToFileURL(resolve(art,'grid-pass-offline.html')).href);await expect(reopened.locator('#source-entry')).toBeDisabled();await expect(reopened.locator('#export')).toBeDisabled();await reopened.locator('#sample').click();await expect(reopened.locator('#source-entry')).toHaveValue('');await reopened.locator('#source-entry').selectOption(sourceId);await reopened.locator('#target-entry').selectOption(targetId);await expect(reopened.locator('#rows tr')).toHaveCount(4);await reopened.close();check('Offline tool copy excludes imported labels, opaque content and filenames, then reopens cleanly');
 await page.locator('#reset').focus();await page.keyboard.press('Enter');await expect(page.locator('#source-entry')).toBeDisabled();await expect(page.locator('#target-entry')).toBeDisabled();await expect(page.locator('#receipt')).toBeDisabled();check('Keyboard clear removes both imported entries, approval and receipt');
 expect(report.pageErrors).toEqual([]);expect(report.consoleErrors).toEqual([]);expect(report.networkRequests).toEqual([]);check('Main and offline pages remain sandboxed with zero script/console errors or network requests');report.status='PASS';
}catch(error){report.status='FAIL';report.failure=error.stack;await shot('failure.png').catch(()=>{});await writeFile(resolve(art,'failure-dom.html'),await page.content().catch(()=>''));throw error;}finally{await writeFile(resolve(art,'browser-report.json'),JSON.stringify(report,null,2)+'\n');await browser.close();}
